spring.application.name=MicroFinanceSoftware

spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp
spring.thymeleaf.enabled=false

#spring.datasource.url=jdbc:mysql://103.14.99.198:3306/bikeAppDB?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.url=jdbc:mysql://localhost:3306/website_db
#spring.datasource.url=jdbc:mysql://103.14.99.198:3306/bikeAppDB?createDatabaseIfNotExist=true

#spring.datasource.username=root
#spring.datasource.password=admin@123456789
#spring.datasource.password=9QT2{gZvm[Gx~b






spring.datasource.url=jdbc:mysql://103.30.72.183:8001/microfinanceDB?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=mysql_admin_user

#spring.datasource.username=root
#spring.datasource.password=admin@123456789
#spring.datasource.password=9QT2{gZvm[Gx~b
spring.datasource.password=Mysql@123$2025#Login@123$DB2026#
#spring.datasource.hikari.maximum-pool-size=3
#spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-test-query=SELECT 1

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

spring.main.allow-circular-references=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB
server.tomcat.max-part-count=200
server.tomcat.max-parameter-count=10000

#mail otp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=infosaisoftwarecompany@gmail.com
spring.mail.password=fnhq stja dnft iyzi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#sms otp


sms.api.url=https://sms.autobysms.com/app/smsapi/index.php?key=${sms.api.key}&campaign=0&routeid=9&type=text&contacts=98012XXXXX&senderid=SMSSPT&msg=Your+otp+is+{#var#}+SELECTIAL&template_id=1707166619134631839
sms.api.key=4668E481546B25



#upload.directory=C:/Users/Hp/OneDrive/Desktop/project1/SamithUrban/src/main\/webapp/Uploads

upload.directory=/opt/tomcat/webapps/MicrofinanceDemo/Uploads

#upload.directory=F:/Samitha Urban/UpdatedMicroFinance/src/main/webapp/Uploads


# Loan Deduction Configuration
loan.deduction.gst-rate=18.0

# MIS (Monthly Income Scheme) Configuration
mis.tds.rate=10.0
mis.tds.threshold.yearly=100.0
mis.premature.penalty.rate=5.0
